name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` and `Automate-rdme-cli-commmand-using-looper` branch
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: GitHub Action
        uses: readmeio/rdme@v8
        with:
          rdme: openapi apispec.json --key=rdme_xn8s9h3bae054946fb53d0dc60f94e385a0ccabaf8846abe81cabf95a6b6ae67ecf73e --id=66cedbd06c0ce20011e49a9e
